module.exports = {
  projects: [
    '<rootDir>/apps/groot-ui',
    '<rootDir>/libs/shared/data-types/global',
    '<rootDir>/libs/shared/data-access/store',
    '<rootDir>/libs/shared/data-access/contracts',
    '<rootDir>/libs/shared/util',
    '<rootDir>/libs/shared/data-access/liquidity',
    '<rootDir>/libs/groot/ui/landing',
    '<rootDir>/libs/groot/ui/swap',
    '<rootDir>/libs/groot/ui/treasury',
    '<rootDir>/libs/groot/ui/liquidity',
    '<rootDir>/libs/groot/ui/yield',
    '<rootDir>/libs/groot/components/header',
    '<rootDir>/libs/groot/components/footer',
    '<rootDir>/libs/groot/ui/footer',
    '<rootDir>/libs/groot/ui/components/header',
    '<rootDir>/libs/groot/ui/landing/components/faq',
    '<rootDir>/libs/groot/components/pool-card',
    '<rootDir>/libs/groot/ui/farming',
  ],
};
